### ISSUE TITLE
I could not change the version of python on a virtual env...

### ISSUE THREAD

**Issue by Jumpo-523** [conda-forge/miniforge#143]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

# packages in environment at /Users/takubojunpei/miniforge3/envs/my_env:
#
# Name                    Version                   Build  Channel

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : my_env
    active env location : /Users/takubojunpei/miniforge3/envs/my_env
            shell level : 2
       user config file : /Users/takubojunpei/.condarc
 populated config files : /Users/takubojunpei/miniforge3/.condarc
          conda version : 4.10.0
    conda-build version : not installed
         python version : 3.9.2.final.0
       virtual packages : __osx=11.2.3=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/takubojunpei/miniforge3  (writable)
      conda av data dir : /Users/takubojunpei/miniforge3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/takubojunpei/miniforge3/pkgs
                          /Users/takubojunpei/.conda/pkgs
       envs directories : /Users/takubojunpei/miniforge3/envs
                          /Users/takubojunpei/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.10.0 requests/2.25.1 CPython/3.9.2 Darwin/20.3.0 OSX/11.2.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```
</details>

**My Conda environment is not working well...
Currently I used python=3.8. I want to change the version of python but the below command doesn't work...**
`conda install python=3.7 `

<details>
```
(my_env) <myname>@Takubos-MacBook-Air ~ % conda install python=3.7  
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - python=3.7

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```
</details>

Thanks in advance.

**Comment by hmaarrfk** [comment]
Sorry. You have a new mac. New hardware needs new software.

We are building up the matrix for Python 3.9 and Python 3.8 on osx + arm.

I believe only Python 3.9 is "officially" supported, but Python 3.8 seems to work. Your mileage may vary.

You can see that the Python 3.7 build is disabled by our "build matrix" due to the "selector" `not (osx and arm64)`
https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml#L605

In my opinion there is little chance of building up Python 3.7 for "Apple silicon" on conda-forge.

Personally, I suspect you will get many other issues similar to this one for at least an other year. If you are still in a position to reconsider purchasing an "intel + apple device" you can use this experience to guide your decision.
