### ISSUE TITLE
Question about OSX M1 installs behavior is no osx-arm64 wheels are available

### ISSUE THREAD

**Issue by richard-moss** [conda-forge/miniforge#172]
**Quick question Re OSX M1 native version:**

*First a quick thanks to everyone for putting miniforge together!*

*Sorry if these Q's are answered somewhere - I did a hunt in the docs and in the issues list and couldn't find the answers explicitly.*

If you use the M1 native OSX version:

- If no osx-arm64 platform wheels are available, what does miniforge default to using instead as the platform?  `no-arch`?  `osx-64`?
- If you do install `osx-64` wheels (ie x86 code), will they still work?  (*I presume yes, as the OS would identify any binaries as x86 binaries, and so automatically run them using Rosetta*)
- If the default to the first Q is no-arch, but osx-64 wheels will happily run via Rosetta, would it be better to default to osx-64 wheels?

*Apologize if this is answered elsewhere and I missed it*
*Quite happy to update docs if needed/helpful based on answers*

**Comment by isuruf** [comment]
> If no osx-arm64 platform wheels are available, what does miniforge default to using instead as the platform? no-arch? osx-64?

If there are no-arch conda packages, they will be used, but osx-64 packages and oxs-arm64 packages are not mixed.

> If you do install osx-64 wheels (ie x86 code), will they still work? (I presume yes, as the OS would identify any binaries as x86 binaries, and so automatically run them using Rosetta)

They wouldn't. If you start python on an arm64 terminal, the extensions need to be arm64 as well. If you start python on a Rossetta terminal, the extensions need to be x86_64.

Another issue is that the python we are distributing via miniforge is arm64 only in comparison to the one in python.org which is universal2 (arm64 and x86_64). So you can't use x86_64 wheels with the osx-arm64 python that miniforge provides. You'll have to create a osx-64 python environment.

> If the default to the first Q is no-arch, but osx-64 wheels will happily run via Rosetta, would it be better to default to osx-64 wheels?

It depends. If all your dependencies are in osx-arm64 conda-forge channel, then it's better to use osx-arm64 because of the speed benefit you may get. If not, either you have to compile some wheels yourself or use osx-64 miniforge.

**Comment by richard-moss** [comment]
@isuruf thanks for the info!

Pity you can't mix them, but understand the limitations

**Comment by jakirkham** [comment]
If there are particular packages you are missing, please consider submitting a PR to add them to [this list]( https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/2e79913d2f8c1e37bb10db84bee3f9d8e882f2cb/recipe/migrations/osx_arm64.txt ), which will put them (and any dependencies) in the queue for migration

**Comment by richard-moss** [comment]
@jakirkham Will do - thanks

**Comment by richard-moss** [comment]
@jakirkham How does this work if it's a pip-only package?  Is the process then to talk directly 
to the pypi package owners, and see if they'll build an osx-arm64 build?

**Comment by jakirkham** [comment]
In that case would suggest [raising an issue on `staged-recipes` about adding the package]( https://github.com/conda-forge/staged-recipes/issues/new?assignees=&labels=Package+request&template=package-request.md&title=%5BPackage+request%5D ) (or preferably submitting a PR to staged-recipes adding it)
