### ISSUE TITLE
When Python 3.10 will be the default Python version?

### ISSUE THREAD

**Issue by strrchr** [conda-forge/miniforge#323]
### Comment:

When Python 3.10 will be the default Python version?

**Comment by miwojc** [comment]
Python 3.10 have better error messages that's a very valid reason to me.

**Comment by sh-cho** [comment]
I want to use pattern matching..

**Comment by hmaarrfk** [comment]
I'm not sure if any of these help the usage of the conda or mamba command. Ultimately one should not really use the base environment for anything else than conda or mamba. Creating environments that have different versions of python installed is entirely possible.

My guess is that we will change the default in 6-18 months. 

Again, because of the ability to create any environment you want, this just isn't a priority.
