### ISSUE TITLE
Package available via conda-forge but not installable with miniforge: hmmlearn

### ISSUE THREAD

**Issue by clstaudt** [conda-forge/miniforge#330]
### Comment:

I would like to understand why sometimes a package is installable from the conda-forge channel (according to the Anaconda package website), but is not found when trying to install with miniforge.

Example: https://anaconda.org/conda-forge/hmmlearn

Attempt to install:
```
╰─ conda install -c conda-forge hmmlearn                                                                                                                               (pyannote) 
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - hmmlearn

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by hmaarrfk** [comment]
Please see: https://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=osx+arm64#apple-silicon-builds

**Comment by hmaarrfk** [comment]
100% request driven. 

There are limited options for CI workflows to actually test things

**Comment by hmaarrfk** [comment]
Even more limit d if you consider the budget of $0

**Comment by clstaudt** [comment]
> Even more limit d if you consider the budget of $0

Sorry to hear that, I thought some of the money I send to NumFocus every year also supports this project.

![Screenshot 2022-07-27 at 17 11 33](https://user-images.githubusercontent.com/875194/181283635-3135ce36-f1b2-4159-ad6f-1d0910bd2b0a.png)

**Comment by hmaarrfk** [comment]
I think generally speaking there is some budget, but it goes quickly if you start to pay for CIs, and not entirely sustainable.

This was my understanding of where things stood in 2018. Since, Azure has given a ton of credits, and it has caused us to move a whole lot of infrastructure there. Even then, it isn't perfect.

For a while, many packages did not even compile natively for arm64 on osx.

In either case, i think the move to cross compilation has been a good one. CIs in general only test a subset of the total usage.

Thank you for your support! 

If you make that PR, you should have your package in a timely manner.
