### ISSUE TITLE
why is conda forge the only channel

### ISSUE THREAD

**Issue by stunlocked1** [conda-forge/miniforge#411]
### Comment:

I dont get it, isn't it like an experimental channel? so we dont get access to libraries that are no longer experimental and moved to nomral channel? and Can i add normal channcel back to it?

**Comment by hmaarrfk** [comment]
This is a conda installer specific conda-forge. Thus we optimize it for usage with our channel.


Please see the conda documentation on how to add channels:
https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-channels.html

**Comment by jdblischak** [comment]
>  isn't it like an experimental channel?

I wanted to quickly clarify this point. Short answer: no, it is not an experimental channel

The relationship between the company Anaconda, Inc. and open source projects such as conda-forge can get confusing, especially since they are often intertwined. With respect to the available channels, here's the least you need to know:

* [conda-forge](https://conda-forge.org/) is a community driven channel. In other words, it's an open source model, where anyone can submit recipes to create new conda packages. If there is a software package you want available as a conda binary, you can [create and submit a recipe](https://conda-forge.org/#contribute) to the conda-forge channel
* The [defaults](https://docs.anaconda.com/anaconda/user-guide/tasks/using-repositories/) channel is maintained by employees at Anaconda, Inc. Since it is maintained by only a few people, it is purposefully kept smaller to be more manageable. I don't even know how one goes about requesting a package be added to defaults. I assume you'd need to be a paying customer
* The conda-forge and defaults channels [are not compatible](https://conda-forge.org/docs/user/tipsandtricks.html#using-multiple-channels) because they pin different versions of key dependencies (eg compilers)

Thus if all the software you need is available from "defaults", then you can install their [miniconda distribution](https://docs.conda.io/en/latest/miniconda.html) (which sets the only channel to "defaults"), and you never have to worry about conda-forge. However, if you need conda packages that are only available from conda-forge, you should install the miniforge distribution (or one if its variants) available from this repository (and avoid the incompatible "defaults" channel).

All of the above (and more) is also nicely summarized in the conda-forge docs [A brief introduction](https://conda-forge.org/docs/user/introduction.html)

**Comment by tdido** [comment]
>     * The conda-forge and defaults channels [are not compatible](https://conda-forge.org/docs/user/tipsandtricks.html#using-multiple-channels) because they pin different versions of key dependencies (eg compilers)

I just wanted to observe for anyone stumbling upon this issue that the latest version of the linked page does indeed say that `conda-forge` and `defaults` are "...not 100% compatible...", but it also states that the incompatibility is solved by using strict channel priorities. Furthermore, it mentions the possibility of some potentially needed dependencies being present in `defaults` and not `conda-forge`.

**Comment by jakirkham** [comment]
Can you please share where it says that?

At this point `conda-forge` is entirely self-contained. So shouldn't need anything from `defaults`

**Comment by jdblischak** [comment]
> Can you please share where it says that?

Go [here](https://conda-forge.org/docs/user/tipsandtricks.html#how-to-fix-it) and then scroll down to the "Note". The text is from a PR way back in 2019 (https://github.com/conda-forge/conda-forge.github.io/pull/766)

> At this point `conda-forge` is entirely self-contained. So shouldn't need anything from `defaults`

@jakirkham 100% agreed. At least on Ubuntu, I haven't installed anything from `defaults` in years. The Note in the docs explicitly mentions `libgcc-ng`, which is available from conda-forge, so I think the Note needs to be edited or removed altogether

```sh
# my current setup to demo libgcc-ng installed from conda-forge
conda config --get channels
## --add channels 'bioconda'   # lowest priority
## --add channels 'conda-forge'   # highest priority
conda list libgcc
## # Name                    Version                   Build  Channel
## _libgcc_mutex             0.1                 conda_forge    conda-forge
## libgcc-ng                 13.1.0               he5830b7_0    conda-forge
```

> it mentions the possibility of some potentially needed dependencies being present in `defaults` and not `conda-forge`.

@tdido thanks for reporting this discrepancy between what I wrote above and the current conda-forge documentation. This needs updating

**Comment by tdido** [comment]
That's excellent. Thank you for clarifying.

**Comment by jakirkham** [comment]
Gotcha ok. That's probably trickier to update since we are trying to show an example of using strict channel priority as well. Have an opened issue ( https://github.com/conda-forge/conda-forge.github.io/issues/1992 ) to discuss how we want to update these docs
