### ISSUE TITLE
Installation fails if not connected to the Internet

### ISSUE THREAD

**Issue by abourrier** [conda-forge/miniforge#419]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

OS: Ubuntu 20.04

When trying to install Mambaforge 22.11 on a platform not connected to the Internet, the installer tries to update some packages right away and I get the following error:
```
critical libmamba Download error (6) Couldn't resolve host name [https://conda.anaconda.org/conda-forge/linux-64/ld_impl_linux-64-2.40-h41732ed_0.conda]
    Could not resolve host: conda.anaconda.org
```

Previous versions of Mambaforge up to 22.09 did not have this problem.

### Installed packages

```shell
No installed package
```

### Environment info

```shell
No environment
```

**Comment by hmaarrfk** [comment]
cc @conda-forge/constructor

**Comment by hmaarrfk** [comment]
I can confirm that this is indeed a bug 
![image](https://user-images.githubusercontent.com/90008/216776355-d83ef125-281b-42dd-9244-1aed971f78de.png)

**Comment by hmaarrfk** [comment]
It might be that we are hitting this bug https://github.com/mamba-org/mamba/issues/2187

**Comment by hmaarrfk** [comment]
I'm somewhat surprised that this issue didn't occur earlier.

It is due to a bug in micromamba: https://github.com/mamba-org/mamba/issues/2187

I think we could accelerate the release of https://github.com/mamba-org/mamba/pull/2265

but the same people that would review a patch proposed for the conda-forge only version would review a patch for the upstream repository. 

I can apply the patch to conda-forge once they accept it there.

**Comment by hmaarrfk** [comment]
Given the code path I've identified it is going through, i'm willing to bet it is still an issue.
