### ISSUE TITLE
Python3.10 detects a vulnerability, when to upgrade python3.11

### ISSUE THREAD

**Issue by hei66** [conda-forge/miniforge#460]
### Comment:

Python3.10 detects a vulnerability, when to upgrade python3.11

**Comment by curtis18** [comment]
Yes, I found the same issue.

**Comment by hmaarrfk** [comment]
> Python3.10 detects a vulnerability, when to upgrade python3.11

I'm not sure what this means, please be specific about the vulnerability you are concerned with. 

You can, create your own installed based on this repository and github actions and customize the default version of python installed.

Otherwise, conda is typically used to create **other** environments, the `base` one belongs to "conda".
