### ISSUE TITLE
Installed on D drive, makes environments on C drive

### ISSUE THREAD

**Issue by OverLordGoldDragon** [conda-forge/miniforge#567]
### Comment:

I completely uninstalled Anaconda, used the [Miniforge Windows installer](https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Windows-x86_64.exe) (Win 11 x64), installed into `D:\miniforge3\`, then used Miniforge Prompt to `mamba install` packages into a virtual environment. They all went into `C:\users\Name\.conda\envs`, instead of `D:\miniforge3\envs` as it would with Anaconda.

How can I change this? And is it too late to "move" the environments (do I need to reinstall miniforge)?

**Comment by nlw1115** [comment]
Hey, have you solved this problem? I tried installing Miniforge on an Ubuntu system, and I installed it in a non-user directory: /opt/miniforge3. However, when I use conda create, the environments are created in the user directory: /home/user. I want the environments to be located within the Miniforge installation path as well, like how Anaconda does it, so that other users can also use the environments I create. But so far, I haven't found a way to do this.
