### ISSUE TITLE
updating conda miniforge

### ISSUE THREAD

**Issue by jontis** [conda-forge/miniforge#63]
When I use 
`$ conda update -n base conda`
to update conda from miniforge, does it understand to stay on miniforge, or will it go to miniconda?

**Comment by romainx** [comment]
Hello,

In this case `conda` is a package like other packages that is available in the `conda-forge` [repository](https://anaconda.org/conda-forge/conda). So this command will update the `conda` package from the `conda-forge` channel because it's the default setting of Miniforge.

```bash
$ conda config --show channels

# channels:
#   - conda-forge
```

Miniforge is the packaging (the installer) of an initial `conda` setup like `Miniconda` is another packaging. So if you have installed Miniforge it is not related at all to Miniconda.

```bash
$ conda --version
# conda 4.9.0

$ conda update -n base conda
# ...
# The following packages will be downloaded:
# 
#     package                    |            build
#     ---------------------------|-----------------
#     conda-4.9.2                |   py38h578d9bd_0         3.0 MB  conda-forge
#     ------------------------------------------------------------
#                                            Total:         3.0 MB
# 
# The following packages will be UPDATED:
# 
#   conda                                4.9.0-py38h924ce5b_1 --> 4.9.2-py38h578d9bd_0

$ conda --version
# conda 4.9.2

$ conda list conda$
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
# conda                     4.9.2            py38h578d9bd_0    conda-forge
```

Best.

**Comment by jontis** [comment]
Many thanks for that explanation. 
Just to clarify if I understood, if it was set up with miniforge, it will remain miniforge then?

**Comment by romainx** [comment]
@jontis Yes. 
I'm not a member of the project but I hope my answer is correct.
I let someone from the team confirm.

**Comment by hmaarrfk** [comment]
Once you "upgrade" you are depending on your channel dependencies to tell you what versions of the software you will get.

If you didn't add the `anaconda` channel, it should simply pull from `conda-forge` which will make you "keep miniforge"

**Comment by romainx** [comment]
Hello @jontis, if you are happy with the answer, you could close the issue.
Many thanks 😄
