### ISSUE TITLE
Doesn't compile sources with NumPy even when NumPy installed in Base env

### ISSUE THREAD

**Issue by slerman12** [conda-forge/miniforge#83]
I installed NumPy into the Base env and then tried to compile some source distributions that depend on NumPy, in particular Pytorch. I compiled Pytorch fine, but it didn't compile with the NumPy commands. This happens when NumPy isn't available during compilation. Compiling other sources led to this same problem too. NumPy, in the base env, isn't recognized by those distributions during compilation.

**Comment by xhochy** [comment]
@slerman12 Please open the issue on a different, more appropriate project. This repo here is for issues with the installer for a basic conda setup but not for general issues inside a conda environmnet. In your case, I guess it is more appropriate to open the issue on the numpy-feedstock or with numpy directly. I also would advise you to give more context (what do you want to achieve? which versions are you using? Include some logs and a reproducible example so that others can recreate your situation).
